### ISSUE TITLE
Controlar la data que puede ver cada usuario

### ISSUE THREAD

**Issue by mjyuja** [pixelhn/pixelpay#2]
Actualmente, si se crea un usuario con los permisos de: 
1. Ver panel principal
2. Ver Historial de cobros
3. Envio de Correos por unidad

Estos son los permisos que quiero que tenga un cobrador. Sin embargo, ellos todavia pueden ver informacion sobre el total de los cobros, o de cobros que no se realizaron dentro de la cuenta.

<img width="1920" alt="screen shot 2017-09-27 at 10 55 20 am 2" src="https://user-images.githubusercontent.com/10138373/30926469-7fd38d34-a372-11e7-82e9-08cab9aeb0ea.png">
<img width="1920" alt="screen shot 2017-09-27 at 10 55 16 am 2" src="https://user-images.githubusercontent.com/10138373/30926470-7fdf277a-a372-11e7-95b5-28687e262ba2.png">

**Comment by pixelhn** [comment]
👍🏻 Resuelto!
