### ISSUE TITLE
Poder poner la cantidad de impuesto a pagar manualmente

### ISSUE THREAD

**Issue by mjyuja** [pixelhn/pixelpay#3]
Basado en reunion con equipo de ventas, es importante que se pueda poner el monto de impuesto por separado para que aparezca asi en la factura. En Global, asi como en otras empresas, hay productos que estan exemptos de impuesto por diferentes motivos - agricultura, etc.  En los pedidos que nos hacen los clientes, van mezclados los productos que estan exemptos y los que no. Si se le aplica un porcentaje a el subtotal, el cliente va creer que estara pagando mas impuesto de la cuenta. 

SAP ya nos factura a nosotros los productos con su respectivo impuesto, asi que seria mejor que solo copiaramos el monto que SAP nos da.

**Comment by pixelhn** [comment]
Excelente, se almacenaría en la tabla la cantidad de los impuestos en todo caso.

**Comment by pixelhn** [comment]
Solved v.44 👍🏻
