### ISSUE TITLE
Option de envío de facturas multiples

### ISSUE THREAD

**Issue by mjyuja** [pixelhn/pixelpay#4]
Queremos poder mandar varias facturas en un solo cobro. Lo mejor seria que para cada factura adicional, se detallara el # de factura, subtotal y impuesto de cada una, y Pixel lo uniera todo en un solo monto y detallando todos los numeros de factura. 

Tenemos clientes que pagan 12 facturas de un solo, asi que esto es para llevar mejor control.

**Comment by pixelhn** [comment]
Solved v.44 👍🏻  - Generación de cobros con detalles
