### ISSUE TITLE
Opcion a Mover usuarios entre grupos

### ISSUE THREAD

**Issue by mjyuja** [pixelhn/pixelpay#7]
Los usuarios que ya estan creados estan dentro de un group que se llama "Sin Categoria". No puedo asignarlos a otro grupo, tengo que borrar su cuenta y asignarles el grupo desde cero, y no quiero que se pierdan los cobros que ya han hecho.

**Comment by mjyuja** [comment]
Al cambiar el nombre de grupo cuando edito el usuario, no se agrupan los que tienen el mismo nombre.

<img width="1155" alt="screen shot 2017-10-10 at 4 02 29 pm" src="https://user-images.githubusercontent.com/10138373/31412979-7d87603e-add4-11e7-97e5-a531d541c0a0.png">

**Comment by pixelhn** [comment]
RESUELTO 👍🏻
